export { default as HomePage} from './HomePage'
export { default as AboutPage} from './AboutPage'
export { default as SkilsPage} from './SkilsPage'
export { default as PortofolioPage} from './PortofolioPage'
export { default as ContactPage} from './ContactPage'